### PR TITLE
change file name

### PR DESCRIPTION
**Pull request by Ibrahim86Ali**
change file name from ibrahim86ali.md to Ibrahim86Ali.md

### CODE REVIEW

**Comment by bermarte** [comment]
@Ibrahim86Ali You deleted 2 files check this https://github.com/HYF-Class20/home/pull/48/files
Always add a file at the time and always use git status before you push to see what you are doing.

**Review by bermarte — CHANGES_REQUESTED** [review]
Please check the last comment in your PR

**Comment by samirm00** [comment]
I did it form my side , this `PR` is no longer needed

**Comment by Ibrahim86Ali** [comment]
> I did it form my side , this `PR` is no longer needed

thanks  Samir

**Pull request closed without merging**
