### PR TITLE
Added saidakf.md bio to Home repo

### PR DESCRIPTION
**Pull request by saidakf**
Bio update To Do:

- [x] Cd, mkdir new file, cd newfile
- [x] Git clone Home repo
- [x] Git init
- [x] Npm i
- [x] git checkout -b saidakf
- [x] npm runs 
- [x] write bio in file saidakf.md
- [x] git add student-bios/saidakf.md
- [x] git commit -m "Added saida bio in saidakf.md"
- [x] git push origin saidakf
- [x] created PR 
- [x] Assigned 3 reviewers & Assignee
- [x] Labels : deliverable, individual, week1
- [x] Milestone: 1. workflows

### CODE REVIEW

**Comment by saidakf** [comment]
Lint Check failed Reasons:

Run npm run format:check
[4](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:5)

[5](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:6)
> school-as-code@1.0.0 format:check
[6](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:7)
> prettier --check ./
[7](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:8)

[8](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:9)
Checking formatting...
[9](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:10)
[warn] student-bios/andreia-negreira.md
[10](https://github.com/HYF-Class20/home/actions/runs/4576722634/jobs/8081228103?pr=62#step:4:11)
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

**Comment by saidakf** [comment]
I fixed the lint fail of [andreia-negreira.md](https://github.com/HYF-Class20/home/pull/62/commits/beb552e18168b1d50f07f5f4c0281ee6e59e97b5)

**Comment by talmurshidi** [comment]
Hi @saidakf 
Please create a new issue and link it to this PR.
You can use this template https://github.com/HYF-Class20/home/issues/2

**Comment by saidakf** [comment]
@talmurshidi I have just done it !

**Review by talmurshidi — APPROVED** [review]

**Pull request merged**
