### PR TITLE
Nana99999.md 

### PR DESCRIPTION
**Pull request by Nana99999**
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [ ] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by samirm00** [comment]
@Nana99999 Please me sure to run all code quality check
`npm run format`
`npm run format:check`
`npm run spell-check`
`npm run lint:ls`
`npm run lint:md`

**Comment by talmurshidi** [comment]
Please do as Samir said. Also, you already have an opened [PR](https://github.com/HYF-Class20/home/pull/53) with the same problem.

**Comment by Nana99999** [comment]
@samirm00 @talmurshidi Hi! Yes I have alredy done all the npm run format check, committed and pushed it but it somehow didn't work 😭

**Comment by talmurshidi** [comment]
@Nana99999 I will follow up with you after the review meeting

**Comment by bermarte** [comment]
You should run
`git pull` and rerun the scripts Samir mentioned.

**Pull request closed without merging**
